### PR TITLE
Fill kick_distance on kickoffs and punts resulting in touchbacks

### LINKED ISSUE #392: pbp.. Kick_distance
In PBP.. Kick_Distance only shows a value when the kickoff is not a touchback. please show a value for all kickoffs. If the kickoff starts On the 35, and the kick is a touchback, the kick distance would be 50 yards.

### PR DESCRIPTION
**Pull request by mrcaseb**
fixes #392 

we now use yardline_100 to determine kick_distance on kickoffs and punts where kick_distance is missing and touchbak == 1

### CODE REVIEW

**Comment by mrcaseb** [comment]
I explicitly decided against parsing the play desc as suggested in https://github.com/nflverse/nflfastR/issues/53#issuecomment-1378329953

Two reasons:
1.) When plays are reversed or replayed, the actual kickdistance isn't the first match of easy patterns
2.) There is a bunch of kickoffs where the play description outputs kick yards beyond the goal line. This is somewhat inconsistent with the rest of all yards variables.

**Comment by guga31bb** [comment]
Should there be something in documentation saying that it's distance to end zone for touchbacks?

**Comment by mrcaseb** [comment]
> Should there be something in documentation saying that it's distance to end zone for touchbacks?

I fear that this confuses more than it helps. With passing_yards, for example, we don't explicitly say that they count from LOS.

**Comment by guga31bb** [comment]
ok sounds good to me!

**Review by guga31bb — APPROVED** [review]

**Comment by mrcaseb** [comment]
> For future reference, see this manual for statisticians https://www.nflgsis.com/gsis/documentation/stadiumguides/guide_for_statisticians.pdf
> 
> 1.5 pages to cover kickoffs smh

It turned out that the definition of kick_distance isn't trivial but fortunately we can extract the correct distance from stat IDs 32, 43, and 44. This is done in #422 

We keep the code chunk of this PR but it shouldn't affect any play as it only changes plays with NA kick_distance

**Pull request merged**
