### PR TITLE
Use default play to predefine column types in `update_db()`

### LINKED ISSUE #324: Use dummy play in update_db() to help predefine column types in some db drivers
It looks like some db drivers define column types with the very first row in the table. 
This can make problems esp. with character columns where the first row is not the longest character string. 

We can try to fix this by adding a dummy play at the very first line in update_db() that wraps all data types and character lengths. 

That dummy play should be saved on sysdata and removed from the table after the function is done. 

https://twitter.com/friscojosh/status/1526288878373507072?s=21&t=oEfim2Cyr45Z7HN3ltXDfQ

### PR DESCRIPTION
**Pull request by mrcaseb**
This resolves #324

Added a new object to sysdata which is a single tibble row that uses random strings for character types with maximum length across the complete dataset (as of 2021).
This should make db drivers to correctly set datatypes in `update_db()` esp. for long string columns.

It is definitely possible that this needs an update at some point, if one or more of the defined string columns isn't big enough.

Thanks to @friscojosh for the idea. I hope this works.

### CODE REVIEW

**Review by tanho63 — COMMENTED** [review]
Can you prefix this with any::tidyverse? https://github.com/nflverse/nflfastR/blob/master/.github/workflows/pkgdown.yaml#L34

**Review by guga31bb — APPROVED** [review]

**Review by tanho63 — CHANGES_REQUESTED** [review]
also just needs to hit redocument to bring in the redact_path arg

**Review by tanho63 — APPROVED** [review]
lgtm, maybe josh would be willing to test new methodology

**Comment by mrcaseb** [comment]
nflreadr sitrep is redocumented. I had to update nflreadr first smh.
I hope the any:: part fixes the tidy verse problem in pkgdown

**Comment by tanho63** [comment]
> encouraging ~~people~~ Seb to always update their packages

**Comment by friscojosh** [comment]
Testing now!

**Comment by mrcaseb** [comment]
Ok, it's definitely broken because I did something stupid, hold on

**Comment by mrcaseb** [comment]
> from 4.3.0.9011
> 
> ```
> ── Update nflfastR Play-by-Play Database ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── nflfastR version 4.3.0.9011 ──
> • 11:13:53 | Purging the complete data table "nflfastR_pbp_test" in your connected database...
> • 11:13:54 | Starting download of 23 seasons between 1999 and 2021...
> Error: Data too long for column 'side_of_field' at row 1 [1406]
> ```

That's interesting. So nflfastR calls (`DBI::dbRemoveTable`)[https://dbi.r-dbi.org/reference/dbremovetable] internally when a complete rebuild is forced. I assume that RMariaDB keeps the field list even when the table is removed.

**Comment by friscojosh** [comment]
OK, I tried a fresh update to a new table and got the same error.

```── Update nflfastR Play-by-Play Database ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── nflfastR version 4.3.0.9011 ──
ℹ 12:17:28 | Can't find the data table "nflfastR_pbp_test2" in your database. Will load the play by play data from scratch.
• 12:17:28 | Starting download of 23 seasons between 1999 and 2021...
Error: Data too long for column 'side_of_field' at row 1 [1406]```

However, `update_db()` works as expected when the table is built manually after binding rows for all available data into one dataframe.

**Pull request merged**
