### PR TITLE
suppress messages if called inside other packages

### LINKED ISSUE #233: Ability to silence messages from functions
Looking to use/import the package in another package and would like option to silence some of the usethis-built messages - possibly with a .quiet argument which can default to FALSE?

### PR DESCRIPTION
**Pull request by mrcaseb**
closes #233 

The messages of all functions except `update_db()` are suppressed when called from a non-global top environment

@tanho63 do you need `update_db()` as well?

### CODE REVIEW

**Comment by tanho63** [comment]
Ehm, I don't think so!

**Comment by tanho63** [comment]
following up on this: I ended up moving to just writing functions that read directly from the github repo, because adding nflfastR as a dependency added a bunch of other mostly-heavyweight dependencies (notably, furrr, future, xgboost, mgcv, fastrmodels etc)

**Comment by mrcaseb** [comment]
Going to close this because I am not super happy with the code changes. We can reopen it if we want those changes

**Comment by tanho63** [comment]
I would be more inclined to export from nflfastR directly if it wasn't so heavyweight (and/or it was split into lighter-weight nflverse packages?) but agree with overall not-merging until it's clearer :)

**Pull request closed without merging**
