### PR TITLE
implement `report()`

### LINKED ISSUE #274: Implement `report()` function that summarizes relevant version information
Since we are often asking people to show us installed versions of various packages we should implement a function that does this automatically for us. 

Something like this:

``` r
report <- function(pkg = NULL, recursive = FALSE){
  if (is.null(pkg)){
    packages <- c(
      "nflreadr",
      "nflfastR",
      "nflseedR",
      "nfl4th",
      "nflplotR",
      "ffsimulator",
      "ffscrapr"
    )
  } else {
    packages <- pkg
  }

  installed <- lapply(packages, nflfastR:::is_installed) |> unlist()

  packages <- packages[installed]

  s <- sessionInfo(packages)

  cli::cat_rule("System Info")
  cli::cat_bullet(s$R.version$version.string)
  cli::cat_bullet("OS: ", s$platform)

  cli::cat_rule("nflverse Packages")
  packages <- s$otherPkgs |> lapply(function(pkg)pkg$Package) |> unlist() |> format()
  versions <- s$otherPkgs |> lapply(function(pkg)pkg$Version) |> unlist()
  cli::cat_bullet(paste0(packages, " (", versions, ")"))

  if (isFALSE(recursive)) return(invisible(NULL))

  cli::cat_rule("nflverse Dependencies")
  deps <-
    tools::package_dependencies(packages, recursive = TRUE) |>
    unlist(use.names = FALSE) |>
    sort() |>
    unique()

  deps <- deps[!deps %in% packages]

  s <- sessionInfo(deps)

  packages <- s$otherPkgs |> lapply(function(pkg)pkg$Package) |> unlist() |> format()
  versions <- s$otherPkgs |> lapply(function(pkg)pkg$Version) |> unlist()
  cli::cat_bullet(paste0(packages, " (", versions, ")"))
}
report()
#> ── System Info ─────────────────────────────────────────────────────────────────
#> • R version 4.1.0 (2021-05-18)
#> • OS: x86_64-apple-darwin17.0 (64-bit)
#> ── nflverse Packages ───────────────────────────────────────────────────────────
#> • nflreadr (1.1.0.05)
#> • nflfastR (4.2.0.9005)
#> • nflseedR (1.0.2)
#> • nfl4th   (1.0.0)
#> • nflplotR (0.0.0.9004)
report("nflreadr", TRUE)
#> ── System Info ─────────────────────────────────────────────────────────────────
#> • R version 4.1.0 (2021-05-18)
#> • OS: x86_64-apple-darwin17.0 (64-bit)
#> ── nflverse Packages ───────────────────────────────────────────────────────────
#> • nflreadr (1.1.0.05)
#> ── nflverse Dependencies ───────────────────────────────────────────────────────
#> • cachem        (1.0.6)
#> • curl          (4.3.2)
#> • data.table    (1.14.0)
#> • fastmap       (1.1.0)
#> • memoise       (2.0.0)
#> • qs            (0.25.1)
#> • RApiSerialize (0.1.0)
#> • rappdirs      (0.3.3)
#> • Rcpp          (1.0.7)
#> • RcppParallel  (5.1.4)
#> • rlang         (0.4.11)
#> • stringfish    (0.15.2)
```

I was thinking about adding this to nflreadr but it is using cli so I have created the issue here. Any thought @tanho63 and @guga31bb ?

### PR DESCRIPTION
**Pull request by mrcaseb**
closes #274 

added the function `report()` that should help us debug problems by outputting version information

### CODE REVIEW

**Comment by mrcaseb** [comment]
This also includes a nice 3 column implementation of dependencies @tanho63 

``` r
nflfastR::report("nflfastR", TRUE)
#> -- System Info -----------------------------------------------------------------
#> * R version 4.1.1 (2021-08-10)
#> * OS: x86_64-w64-mingw32/x64 (64-bit)
#> -- Packages --------------------------------------------------------------------
#> * nflfastR (4.2.0.9006)
#> -- Dependencies ----------------------------------------------------------------
#> * cli        (3.0.1)     * codetools   (0.2-18)    * cpp11      (0.3.1) 
#> * crayon     (1.4.1)     * curl        (4.3.2)     * data.table (1.14.0)
#> * digest     (0.6.27)    * dplyr       (1.0.7)     * ellipsis   (0.3.2) 
#> * fansi      (0.5.0)     * fastrmodels (1.0.2)     * furrr      (0.2.3) 
#> * future     (1.22.1)    * generics    (0.1.0)     * globals    (0.14.0)
#> * glue       (1.4.2)     * janitor     (2.1.0)     * jsonlite   (1.7.2) 
#> * lattice    (0.20-44)   * lifecycle   (1.0.0)     * listenv    (0.8.0) 
#> * lubridate  (1.7.10)    * magrittr    (2.0.1)     * Matrix     (1.3-4) 
#> * mgcv       (1.8-36)    * nlme        (3.1-152)   * parallelly (1.28.1)
#> * pillar     (1.6.2)     * pkgconfig   (2.0.3)     * progressr  (0.8.0) 
#> * purrr      (0.3.4)     * R6          (2.5.1)     * Rcpp       (1.0.7) 
#> * rlang      (0.4.11)    * snakecase   (0.11.0)    * stringi    (1.7.4) 
#> * stringr    (1.4.0)     * tibble      (3.1.4)     * tidyr      (1.1.3) 
#> * tidyselect (1.1.1)     * utf8        (1.2.2)     * vctrs      (0.3.8) 
#> * xgboost    (1.4.1.1)   * codetools   (0.2-18)    * cpp11      (0.3.1)
```

<sup>Created on 2021-09-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Review by guga31bb — COMMENTED** [review]
If we use the new pipe we have to increment the R version requirement in DESCRIPTION, right? I would be inclined to not do this (I can't even test this bc I don't have this version of R, lol)

**Comment by mrcaseb** [comment]
> 
> 
> If we use the new pipe we have to increment the R version requirement in DESCRIPTION, right? I would be inclined to not do this (I can't even test this bc I don't have this version of R, lol)

Good catch! That was a mistake. Will fix

**Comment by tanho63** [comment]
I'm not opposed to bringing in cli at nflreadr level if it makes more sense for this to live there, does it make more sense?

**Comment by guga31bb** [comment]
Ok looks good to me!

**Comment by mrcaseb** [comment]
> 
> 
> I'm not opposed to bringing in cli at nflreadr level if it makes more sense for this to live there, does it make more sense?

I wanted to test the function with cli and found two special cases that need to be caught haha. Adding `cli` to nflreadr would also add `glue` and I'd like to keep it light so I would put `report` into nflfastR tbh

``` r
nflfastR::report("cli", TRUE)
#> -- System Info -----------------------------------------------------------------
#> * R version 4.1.1 (2021-08-10)
#> * OS: x86_64-w64-mingw32/x64 (64-bit)
#> -- Packages --------------------------------------------------------------------
#> * cli (3.0.1)
#> -- Dependencies ----------------------------------------------------------------
#> * glue (1.4.2)
```

**Comment by tanho63** [comment]
trouble to me is it becomes annoying to re-export a report function if we're debugging anything other than nflfastR?

**Comment by mrcaseb** [comment]
> trouble to me is it becomes annoying to re-export a report function if we're debugging anything other than nflfastR?

I am not sure what that means tbh. I assume most users that are asking us nflverse related questions will have installed nflfastR anyways. And if that's not the case they just need to install it an run the function. Sounds like a fair price for not adding another two deps to nflreadr. But that is not a strong opinion.

**Comment by mrcaseb** [comment]
Going to merge this now. We can still move the function in another package if we feel like it is necessary. It's not a function that is a typical use case in any user script so moving it is not a big deal at all

**Pull request merged**
